### ISSUE TITLE
When IO0 is connected to CR10 display screen, the reset will be invalid

### ISSUE THREAD

**Issue by dream111119** [vivian-ng/MRR_ESPE#7]
Hello, I have trouble using IO0. I can't use the reset function. After clicking reset, I didn't enter the main program. Is there any way for IO0?

**Comment by luc-github** [comment]
if IO0 is connected to ground at start, the board go to flash mode (https://github.com/espressif/esptool/wiki/ESP32-Boot-Mode-Selection#gpio0)  - if you use IO0 be sure it is not connected to GND at start or your board will not start

**Comment by vivian-ng** [comment]
@dream111119 Please see if this [related issue](https://github.com/maplerainresearch/MRR_ESPE/issues/3) helps. Sometimes, the control knob on the LCD pulls the BTN_ENC1 to GND, which causes a problem for the ESP32.

If the reset button on the main board works, it could be an issue with the LCD controller itself. Make sure the connections from the LCD are properly connected to their required connectors on the main board.

**Comment by vivian-ng** [comment]
@dream111119 If the issue is resolved, please share with everyone what was done to resolve the issue so that others with such an issue next time can try.

**Comment by vivian-ng** [comment]
Closed due to no further response.
